name: DockerHub Push

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Backend Docker image
      run: docker build --tag mentalpirate/flask-backend:$(date +%s) backend
      working-directory: backend
    - name: Build the Frontend Docker image
      run: docker build --tag mentalpirate/express-frontend:$(date +%s) frontend
      working-directory: frontend
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: push backend to docker registry
      run: docker push mentalpirate/flask-backend:$(date +%s)
    - name: push frontend to docker registry
      run: docker push mentalpirate/express-frontend:$(date +%s)
